### ISSUE TITLE
I want to redirect into my application when user accept call. not to native calling screen

### ISSUE THREAD

**Issue by saurabh874** [MrHertal/react-native-twilio-phone#3] opened 2020-10-28 10:12 UTC
is there anyway to redirect into own application's screen when user accept call. not to native calling screen? and native screen should not display after accept call?

**Comment by MrHertal** [comment] 2020-10-28 11:44
Hi,

If I understand correctly, you want to stay on your application when accepting a call and not going on native UI.
On iOS this is already the case. But on Android native UI is displayed over your app when accepting a call.

This is due to the call to CallKeep [setCurrentCallActive](https://github.com/react-native-webrtc/react-native-callkeep#setcurrentcallactive). This is called [here](https://github.com/MrHertal/react-native-twilio-phone/blob/520c9b9f78da1be1b2044375d9c085b124f2090d/src/RNTwilioPhone.ts#L206) when call is connected.

**first option**: create a local copy of `RNTwilioPhone` and remove this line. Your app will be in foreground and native UI in background. But the problem is that you won't be able to use hold/mute/digits functionalities on native UI.

**second option**: try to call CallKeep [backToForeground](https://github.com/react-native-webrtc/react-native-callkeep#backtoforeground) after call has connected.

**Comment by saurabh874** [comment] 2020-10-28 11:57
@MrHertal  then which function i have to call for iOS. because this is i am facing in iOS only when app is in background or kill mode. it always open native UI when accept a call. even i do not want to show native UI in all are modes.

**Comment by MrHertal** [comment] 2020-10-28 13:07
I don't think that is possible on iOS because from what I understand, incoming VoIP push must be reported asap to CallKit, even if app is not awake.

**Closed as completed** 2020-10-30 10:44 UTC
